In [1]:
from numpy import *

4*4的随机数组

In [2]:
random.rand(4,4)

数组转换为矩阵

In [6]:
rand_mat=mat(random.rand(4,4))
rand_mat

matrix([[0.81713114, 0.3862322 , 0.66778569, 0.00646356],
        [0.8714868 , 0.2641668 , 0.67485315, 0.93028844],
        [0.31749213, 0.35582996, 0.96677695, 0.44561322],
        [0.92282937, 0.68986233, 0.14080474, 0.88762778]])

矩阵求逆

In [7]:
inv_rand_mat=rand_mat.I
inv_rand_mat

matrix([[ 1.09780055,  0.88435413, -1.33722537, -0.26352806],
        [-0.02341648, -2.1719871 ,  1.29547489,  1.6261829 ],
        [ 0.17885985,  0.16691141,  0.88465986, -0.62035909],
        [-1.15151055,  0.7421604 ,  0.243083  ,  0.23511952]])

In [8]:
rand_mat*inv_rand_mat#结果应该是单位矩阵

matrix([[ 1.00000000e+00, -5.70411697e-17,  1.02151262e-16,
          8.25460785e-17],
        [-2.01325111e-16,  1.00000000e+00, -2.79074668e-17,
          7.02431385e-17],
        [-2.72513585e-17, -4.25020447e-17,  1.00000000e+00,
          6.80083315e-17],
        [-2.43983702e-16, -1.94040476e-17, -8.77565777e-17,
          1.00000000e+00]])

In [9]:
my_eye=rand_mat*inv_rand_mat
my_eye-eye(4) #应为全0

matrix([[-2.22044605e-16, -5.70411697e-17,  1.02151262e-16,
          8.25460785e-17],
        [-2.01325111e-16,  0.00000000e+00, -2.79074668e-17,
          7.02431385e-17],
        [-2.72513585e-17, -4.25020447e-17,  0.00000000e+00,
          6.80083315e-17],
        [-2.43983702e-16, -1.94040476e-17, -8.77565777e-17,
          0.00000000e+00]])